### ISSUE TITLE
Token Saturn Verificando mas não logando no mta

### ISSUE THREAD

**Issue by revoltzxp** [lowpixelgg/lowpixel#1]
Boa noite, estava ligando o gamemode em conjunto com o saturn e o launcher, para eu conseguir entrar em uma conta no jogo, apos logar no launcher e entrar no jogo, puxa o token certo do saturn, mas aparece que eu estou usando um parte normal do mta, um cara me ajudou, mas nao aparece a pixel_queue, o pixel_lobby, testei colocar um outputChatBox para ver se tava criando o socket e deu true, testei colocar um kickPlayer pra quando o player entrar e se não logar, kickar, aconteceu o previsto, fui kickado do servidor, tentamos varias coisas, mas sempre acontece o mesmo, sou kickado, e nao loga.

**Comment by vitor3g** [comment]
> Boa noite, estava ligando o gamemode em conjunto com o saturn e o launcher, para eu conseguir entrar em uma conta no jogo, apos logar no launcher e entrar no jogo, puxa o token certo do saturn, mas aparece que eu estou usando um parte normal do mta, um cara me ajudou, mas nao aparece a pixel_queue, o pixel_lobby, testei colocar um outputChatBox para ver se tava criando o socket e deu true, testei colocar um kickPlayer pra quando o player entrar e se não logar, kickar, aconteceu o previsto, fui kickado do servidor, tentamos varias coisas, mas sempre acontece o mesmo, sou kickado, e nao loga.

Modifique o código para que pule o pixel_queue.

**Comment by mostov003** [comment]
Olá , existe algum arquivo SQL que eu possa ter para vinculá-lo com o servidor?
